updating for current RC 7.x and MongoDB 7.0

diff --git a/doc/docker/development/docker-compose.yml b/doc/docker/development/docker-compose.yml
--- a/doc/docker/development/docker-compose.yml
+++ b/doc/docker/development/docker-compose.yml
@@ -142,7 +142,7 @@ services:
     - egroupware
     - push
     - collabora-key
-    #- rocketchat
+    - rocketchat
     container_name: egroupware-nginx
     restart: always
 
@@ -227,67 +227,59 @@ services:
     volumes:
       - $PWD/data/default/loolwsd:/tmp/coolwsd
 
-  # Rocket.Chat server
-  #rocketchat:
-  #  image: quay.io/egroupware/rocket.chat:stable6
-  #  command: >
-  #      sh -c
-  #        "while true; do
-  #          node main.js &&
-  #          s=$$? && break || s=$$?;
-  #          echo \"Could not reach MongoDB. Waiting 5 secs ...\";
-  #          sleep 5;
-  #        done; (exit $$s)"
-  #  restart: unless-stopped
-  #  volumes:
-  #    - $PWD/data/default/rocketchat/uploads:/app/uploads
-  #  # if EGroupware uses a certificate from a private CA, OAuth authentication will fail, you need to:
-  #  # - have the CA certificate stored at /etc/egroupware-docker/private-ca.crt
-  #  # - uncomment the next 2 lines about the private CA:
-  #  # - /etc/egroupware-docker/private-ca.crt:/usr/local/share/ca-certificates/private-ca.crt:ro
-  #  environment:
-  #    # - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/private-ca.crt
-  #    # IMPORTANT: change ROOT_URL to your actual url eg. https://domain.com/rocketchat
-  #    - ROOT_URL=http://localhost/rocketchat
-  #    - PORT=3000
-  #    - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0&directConnection=true
-  #    - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true
-  #  #     - HTTP_PROXY=http://proxy.domain.com
-  #  #     - HTTPS_PROXY=http://proxy.domain.com
-  #  depends_on:
-  #    - mongo
-  #  container_name: rocketchat
-  #  # set the ip-address of your docker host AND your official DNS name so Rocket.Chat
-  #  # can access EGroupware without the need to go over your firewall
-  #  #extra_hosts:
-  #  #- "my.host.name:ip-address"
+  rocketchat:
+    image: quay.io/egroupware/rocket.chat:stable7
+    command: >
+      sh -c
+        "while true; do
+          node main.js &&
+          s=$$? && break || s=$$?;
+          echo \"Could not reach MongoDB. Waiting 5 secs ...\";
+          sleep 5;
+        done; (exit $$s)"
+    restart: unless-stopped
+    volumes:
+      - $PWD/data/default/rocketchat/uploads:/app/uploads
+    # if EGroupware uses a certificate from a private CA, OAuth authentication will fail, you need to:
+    # - have the CA certificate stored at /etc/egroupware-docker/private-ca.crt
+    # - uncomment the next 2 lines about the private CA:
+    # - /etc/egroupware-docker/private-ca.crt:/usr/local/share/ca-certificates/private-ca.crt:ro
+    environment:
+      - ROOT_URL=http://localhost/
+      - PORT=3000
+      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0&directConnection=true
+      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true
+    depends_on:
+      - mongo
+    ports:
+      - 127.0.0.1:3000:3000
+    container_name: rocketchat
 
-  # MongoDB for Rocket.Chat
-  #mongo:
-  #  image: mongo:5.0
-  #  restart: unless-stopped
-  #  volumes:
-  #    - mongo:/data/db
-  #    - $PWD/data/default/rocketchat/dump:/dump
-  #  command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
-  #  container_name: rocketchat-mongo
+  mongo:
+    image: mongo:7.0
+    restart: unless-stopped
+    volumes:
+      - mongo:/data/db
+      - $PWD/data/default/rocketchat/dump:/dump
+    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
+    container_name: rocketchat-mongo
   # this container's job is just run the command to initialize the replica set.
   # it will run the command and remove himself (it will not stay running)
-  #mongo-init-replica:
-  #  image: mongo:5.0
-  #  command: >
-  #      bash -c
-  #        "for (( ; ; )); do
-  #          mongo mongo/rocketchat --eval \"
-  #            rs.initiate({
-  #              _id: 'rs0',
-  #              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
-  #          s=$$? && break || s=$$?;
-  #          echo \"Could not reach MongoDB. Waiting 5 secs ...\";
-  #          sleep 5;
-  #        done; (exit $$s)"
-  #  depends_on:
-  #    - mongo
+  mongo-init-replica:
+    image: mongo:7.0
+    command: >
+      bash -c
+        "for (( ; ; )); do
+          mongosh mongo/rocketchat --eval \"
+            rs.initiate({
+              _id: 'rs0',
+              members: [ { _id: 0, host: 'localhost:27017' } ]})\" 2>&1 | grep 'MongoServerError: already initialized' &&
+          s=$$? && break || s=$$?;
+          echo \"Could not reach MongoDB. Waiting 5 secs ...\";
+          sleep 5;
+        done; (exit $$s)"
+    depends_on:
+      - mongo
 
   # phpMyAdmin
   phpmyadmin:
